name: Wake-Up Render Every Minute

on:
  schedule:
    # ตั้งให้ทำงานทุก 1 นาที
    - cron: '*/1 * * * *'
  workflow_dispatch: # ทำให้สามารถ trigger ด้วยตัวเองแบบ manual ได้
jobs:
  wakeup_test:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Request
        env:
          TEST_URL: "https://httpbin.org/get"
        run: |
          curl -X GET "$TEST_URL"
