name: Test GitHub Actions Wake-Up

on:
  push: # Trigger when there's a new push
    branches:
      - main

jobs:
  wakeup_test:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Request
        env:
          TEST_URL: "https://httpbin.org/get"
        run: |
          curl -X GET "$TEST_URL"
