name: Test GitHub Actions Wake-Up

on:
  schedule:
    # ตั้งให้ทำงานทุก 1 นาที
    - cron: '*/1 * * * *'

jobs:
  wakeup_test:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Request
        env:
          TEST_URL: "https://httpbin.org/get"
        run: |
          curl -X GET "$TEST_URL"
